/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisualIntelligenceRouteImport } from './routes/visual-intelligence'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecordedMissionsRouteImport } from './routes/recorded-missions'
import { Route as LiveRouteImport } from './routes/live'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AirborneRouteImport } from './routes/airborne'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordedMissionsMissionIdRouteImport } from './routes/recorded-missions/$missionId'

const VisualIntelligenceRoute = VisualIntelligenceRouteImport.update({
  id: '/visual-intelligence',
  path: '/visual-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedMissionsRoute = RecordedMissionsRouteImport.update({
  id: '/recorded-missions',
  path: '/recorded-missions',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AirborneRoute = AirborneRouteImport.update({
  id: '/airborne',
  path: '/airborne',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordedMissionsMissionIdRoute =
  RecordedMissionsMissionIdRouteImport.update({
    id: '/$missionId',
    path: '/$missionId',
    getParentRoute: () => RecordedMissionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airborne': typeof AirborneRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/recorded-missions': typeof RecordedMissionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
  '/recorded-missions/$missionId': typeof RecordedMissionsMissionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airborne': typeof AirborneRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/recorded-missions': typeof RecordedMissionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
  '/recorded-missions/$missionId': typeof RecordedMissionsMissionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airborne': typeof AirborneRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/live': typeof LiveRoute
  '/recorded-missions': typeof RecordedMissionsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/visual-intelligence': typeof VisualIntelligenceRoute
  '/recorded-missions/$missionId': typeof RecordedMissionsMissionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airborne'
    | '/alerts'
    | '/analytics'
    | '/live'
    | '/recorded-missions'
    | '/settings'
    | '/visual-intelligence'
    | '/recorded-missions/$missionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airborne'
    | '/alerts'
    | '/analytics'
    | '/live'
    | '/recorded-missions'
    | '/settings'
    | '/visual-intelligence'
    | '/recorded-missions/$missionId'
  id:
    | '__root__'
    | '/'
    | '/airborne'
    | '/alerts'
    | '/analytics'
    | '/live'
    | '/recorded-missions'
    | '/settings'
    | '/visual-intelligence'
    | '/recorded-missions/$missionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirborneRoute: typeof AirborneRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LiveRoute: typeof LiveRoute
  RecordedMissionsRoute: typeof RecordedMissionsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  VisualIntelligenceRoute: typeof VisualIntelligenceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visual-intelligence': {
      id: '/visual-intelligence'
      path: '/visual-intelligence'
      fullPath: '/visual-intelligence'
      preLoaderRoute: typeof VisualIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded-missions': {
      id: '/recorded-missions'
      path: '/recorded-missions'
      fullPath: '/recorded-missions'
      preLoaderRoute: typeof RecordedMissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airborne': {
      id: '/airborne'
      path: '/airborne'
      fullPath: '/airborne'
      preLoaderRoute: typeof AirborneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recorded-missions/$missionId': {
      id: '/recorded-missions/$missionId'
      path: '/$missionId'
      fullPath: '/recorded-missions/$missionId'
      preLoaderRoute: typeof RecordedMissionsMissionIdRouteImport
      parentRoute: typeof RecordedMissionsRoute
    }
  }
}

interface RecordedMissionsRouteChildren {
  RecordedMissionsMissionIdRoute: typeof RecordedMissionsMissionIdRoute
}

const RecordedMissionsRouteChildren: RecordedMissionsRouteChildren = {
  RecordedMissionsMissionIdRoute: RecordedMissionsMissionIdRoute,
}

const RecordedMissionsRouteWithChildren =
  RecordedMissionsRoute._addFileChildren(RecordedMissionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirborneRoute: AirborneRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  LiveRoute: LiveRoute,
  RecordedMissionsRoute: RecordedMissionsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  VisualIntelligenceRoute: VisualIntelligenceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
